name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['9.0']

    steps:
      - uses: actions/checkout@v4
      - name: Setp dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

        # You can test your matrix by priting the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      - name: Build Restoring Dependencies
        run: dotnet restore